### PR TITLE
Github Actions failure: macos " No installed conda 'base' environment found at !"

### PR DESCRIPTION
**Pull request by mathieuboudreau**
## Checklist

- [ ] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've linked relevant issues in the PR body
- [ ] I've applied [the relevant labels](https://intranet.neuro.polymtl.ca/geek-tips/contributing#pr-labels-a-href-pr-labels-id-pr-labels-a) to this PR
- [ ] I've added relevant tests for my contribution
- [ ] I've updated the documentation and/or added correct docstrings
- [ ] I've assigned a reviewer
- [ ] I've consulted [ADS's internal developer documentation](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution) to ensure my contribution is in line with any relevant design decisions

## Description

We've recently started getting this failure on the macos CI:

```shell
Error: No installed conda 'base' environment found at !If you are using this action in a self-hosted runner that already provides its own Miniconda installation, please specify its location with a `CONDA` environment variable. If you want us to download and install Miniconda or Miniforge for you, add `miniconda-version: "latest"` or `miniforge-version: "latest"`, respectively, to the parameters for this action.
```

https://github.com/axondeepseg/axondeepseg/actions/runs/8918691441/job/24493688432

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
Here's the cause that was reported: https://github.com/conda-incubator/setup-miniconda/issues/344

**Comment by mathieuboudreau** [comment]
Seems like forcing the  mac runner to version 12 instead of latest did the trick (not sure why 13 didn't). This is a temporary fix until they resolve it on the https://github.com/conda-incubator/setup-miniconda/issues/344 side

**Comment by mathieuboudreau** [comment]
In terms of the required checks, the only options available were macos-latest or macos-13, so I disabled the macos matrix test as a required check for now; we'll need to reinstate it when we can set it to latest again

**Review by Stoyan-I-A — APPROVED** [review]
Approving for now. We'll have to investigate how to add back the latest os in the future.

**Pull request merged**
