### PR TITLE
Add morphometrics algorithms description

### PR DESCRIPTION
**Pull request by hermancollin**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://intranet.neuro.polymtl.ca/geek-tips/contributing#pr-labels-a-href-pr-labels-id-pr-labels-a) to this PR
- [ ] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [x] I've assigned a reviewer
- [x] I've consulted [ADS's internal developer documentation](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution) to ensure my contribution is in line with any relevant design decisions

## Description

This PR adds some details about the morphometrics computation. In particular, the diameter and eccentricity estimations are detailed. I would also like to eventually describe how the perimeter is computed, but #776 needs to be adressed first.

### CODE REVIEW

**Comment by hermancollin** [comment]
um the doc build fails due to "excessive memory consumption"? I'll have to look into this tomorrow, not sure what the problem is.

**Comment by hermancollin** [comment]
@mathieuboudreau I'm a bit stumped here. Initially the doc build failed (timed out), but then I re-triggered the tests (which did not re-trigger the rtd build unfortunately) and even the tests failed with `coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs`.

Any idea what's going on?

**Comment by mathieuboudreau** [comment]
Have you seen this thread @hermancollin ? https://github.com/lemurheavy/coveralls-public/issues/1435

Maybe a token issue or their API has been updated. We could also try removing this project on coveralls and re-adding it. Do you have access?

**Comment by mathieuboudreau** [comment]
> > Have you seen this thread @hermancollin ? [lemurheavy/coveralls-public#1435](https://github.com/lemurheavy/coveralls-public/issues/1435)
> > Maybe a token issue or their API has been updated. We could also try removing this project on coveralls and re-adding it. Do you have access?
> 
> I don't think I have access. I saw the thread but why would it fail now? You pushed PRs with changes to the doc this month

No idea why it would fail this morning; a test passed last night!
Screenshot 2023-12-05 at 12 59 58 PM

I just started a separate branch PR to see how it behaves there

**Comment by mathieuboudreau** [comment]
I see that on RTD, the error is this: "Error

Build exited due to excessive memory consumption
"

Likely, something changed in one of the dependencies and it messed up things (maybe version resolution?).

**Comment by hermancollin** [comment]
Ahh! It works now. Thank you @mathieuboudreau. The new part in the doc can be seen here: https://axondeepseg--777.org.readthedocs.build/en/777/documentation.html#implementation-details

**Review by mathieuboudreau — APPROVED** [review]
I just slightly changed the equations for clarity - the rest reads well to me!

**Pull request merged**
