### PR TITLE
Add napari plugin, set as default GUI tool

### LINKED ISSUE #404: Test other software package offering "easy label" and segmentation of images
### Context

A couple of recent publications and software packages offer the possibility to upload an image in a GUI (e.g. ImageJ, FIJI, etc.), perform an easy labeling, train a model on-the-fly and apply to the rest of the image (or other images).

Examples of articles include:
- [falk2018.pdf](https://github.com/neuropoly/axondeepseg/files/5604871/falk2018.pdf)
- [haberl2018.pdf](https://github.com/neuropoly/axondeepseg/files/5604873/haberl2018.pdf)
- [s41592-019-0582-9.pdf](https://github.com/neuropoly/axondeepseg/files/5604880/s41592-019-0582-9.pdf)

And software:
- https://github.com/qupath/qupath/wiki
- https://imagej.nih.gov/ij/
- https://fiji.sc/
- https://microdraw.pasteur.fr/
- https://opensource.google/projects/neuroglancer

### Proposal

It would be nice to assess the effectiveness of these packages wrt. what ADS can offer in terms of:
- user friendliness
- performance (Dice score)
- time spent for training/prediction
- outputs (morphometric calculations, etc.)

### Dataset

To do this comparison, we propose to use the following dataset, which includes an image and its ground truth (for training), and another image without ground truth (for testing): [data_train-test.zip](https://github.com/neuropoly/axondeepseg/files/5604892/data_train-test.zip)

Other possible datasets:
- nerve seg (email 2020-12-03)

### LINKED ISSUE #681: Try out using a Napari plugin as a GUI for ADS
Related to #404 

The idea is to write a plugin for https://github.com/napari/napari to see if it fits our needs.

### PR DESCRIPTION
**Pull request by Stoyan-I-A**
## Checklist

- [X] I've given this PR a concise, self-descriptive, and meaningful title
- [X] I've linked relevant issues in the PR body
- [X] I've applied [the relevant labels](https://intranet.neuro.polymtl.ca/geek-tips/contributing#pr-labels-a-href-pr-labels-id-pr-labels-a) to this PR
- [ ] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [x] I've assigned a reviewer
- [X] I've consulted [ADS's internal developer documentation](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution) to ensure my contribution is in line with any relevant design decisions

## Description
The goal of this PR is to replace the FSLeyes plugin with a plugin for napari.

## TODO
- [x]  Determine how the installation should be done by the users
- [x] Update documentation
- [x] Add docstrings to the plugin code
- [ ] ~Nice to have: add tooltips to buttons~

## How to test:
- ~Follow the steps to install ADS~
- ~Once ADS is installed, follow the instructions **starting from step 5** of https://github.com/axondeepseg/napari-plugin/blob/main/README.md~

New instructions:

```
git clone https://github.com/axondeepseg/axondeepseg.git ads_napari
cd ads_napari
git checkout sia/add_napari_plugin
conda env create -n ads_napari
conda activate ads_napari
pip install -e . plugins/
napari
```
## Linked issues
Resolves #681, resolves #404

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
@Stoyan-I-A I've made a few minor changes which now substantially simplify the installation procedure.

To install from this branch, all one needs to do is follow the basic ADS installation procedure, with one minor change during the `pip install` step.

```
git clone https://github.com/axondeepseg/axondeepseg.git ads_napari
cd ads_napari
git checkout sia/add_napari_plugin
conda env create -n ads_napari
conda activate ads_napari
pip install -e . plugins/
```

And then run `napari` as usual.

Would you mind testing it out on your end to see if it works as seamlessly as it does for me?

**Comment by mathieuboudreau** [comment]
The tests are failing due to timeouts from long conda resolve times, but it doesn't appear to be due to my changess a the "passing" green checkmarks for [39329c0](https://github.com/axondeepseg/axondeepseg/pull/726/commits/39329c0fa903b6ec250b40e6175a237823e7ff3e) just before my commits only checked the readthedocs build for some reason, whereas mine are running all the tests. I also found locally during my testing that it was taking quite a while to resolve the envs, which I am guessing are from the replacement of `fsleyes` to `napari` in the conda reqs. I recall we had a similar issue when we introduce `fsleyes` in the environment file, and after playing around for a long time, ended up needing to "fix" certain other dependency versions in order to need less conflict resolutions between dependencie.

**Comment by mathieuboudreau** [comment]
I think to resolve the very long package resolution time, we may need to resort in implementeding `mamba` instructions per #680. I just tried locally and the installation of this branch took lest than a minute with mamba, the only caveat being that I had to install mambaforge which overrides the default conda in the terminal path, which would be annoying (very) for user with already existing environments in their conda install. The need for a way around this is partly why I stalled #680, so we may need to explore alternative install instsructios (eg see what other packages in the lab are doing and if we can leverage some of their work)

**Comment by mathieuboudreau** [comment]
@Stoyan-I-A Cool! I didn't think of testing it with the pip install instead - great idea! And now the tests pass.

I'll test it locally too now for me to make sure it runs the same.

**Comment by Stoyan-I-A** [comment]
@mathieuboudreau I have tested your install instructions and they worked on my side.

**Comment by mathieuboudreau** [comment]
I've made changed the state of this branch to `active` on ReadTheDocs, so now the documentation will build for each push to this branch. You can now preview the documentation for this branch here: https://axondeepseg.readthedocs.io/en/sia-add_napari_plugin/

**Comment by mathieuboudreau** [comment]
This documentation section, https://axondeepseg.readthedocs.io/en/sia-add_napari_plugin/documentation.html?highlight=fsleyes#graphical-user-interface-gui, needs to be updated. I can write something up. One thing we'll need to do, either in this PR or open an issue for, is create a YouTube tutorial for the napari plugin like we did for our FSLeyes one: https://www.youtube.com/watch?v=ImElcp9_k6Y

**Comment by mathieuboudreau** [comment]
I've updated most of the documentation for napari. 

The only section I didn't change is the manual segmentation one, https://axondeepseg.readthedocs.io/en/sia-add_napari_plugin/documentation.html?highlight=fsleyes#manual-correction-of-segmentation-masks, because I don't quite know how to use the manual segmentation tools in napari yet, and also his detailed GDoc will also need to be changed: https://docs.google.com/document/d/1S8i96cJyWZogsMw4RrlQYwglcOWd3HrM5bpTOJE4RBQ/edit?usp=sharing

**Comment by mathieuboudreau** [comment]
Actually, not changed, but we need to create a new GDoc for the napari instructions (we'll want to keep the old doc so that older versions of the documentation still point to the FSLeyes GDoc)

**Comment by mathieuboudreau** [comment]
@Stoyan-I-A I've added docstrings in the plugin for all the classes/methods, but could use your help in ensuring that the information is correct since you wrote the code.

**Comment by mathieuboudreau** [comment]
For the tooltips, if you think it will take some time to implement, I'd say let's open issues for them so that we can release this update quicker.

Besides that, from your initial to-do list, I think we're only really missing instructions for the manual segmentation, and then could un-draft this PR for review.

**Comment by Stoyan-I-A** [comment]
Thank you @mathieuboudreau for adding the changes. I will look at them in the next few days.

**Comment by Stoyan-I-A** [comment]
I changed some of the docstrings. I mostly removed some text because I found it was either redundant OR that it was too long and could become a risk if the code is modified in the future and the dev forgets to update the docstring

**Comment by mathieuboudreau** [comment]
> I changed some of the docstrings. I mostly removed some text because I found it was either redundant OR that it was too long and could become a risk if the code is modified in the future and the dev forgets to update the docstring

Thank @Stoyan-I-A ! Yes I felt that too, I cleaned a lot of them up beforehand so sorry I missed some of the verbose ones!

**Comment by mathieuboudreau** [comment]
@Stoyan-I-A I've written the section on manual segmentation using the Napari plugin in the documentation, and also recorded a short video tutorial. I've opened an issue for the tooltips feature you mentionne (#731).

I think the PR is now ready for review. Although you can't approve his PR (you created it), if you could review the parts I've added and give written approval, I'll review your plugin code and approve this PR (I only expect minor suggestions, from my earlier pass, and generally using it).

**Comment by Stoyan-I-A** [comment]
Thank you @mathieuboudreau. I will look at it in the upcoming days.

**Comment by Stoyan-I-A** [comment]
I checked the updated documentation. About the video: we have a youtube channel for AxonDeepSeg (https://www.youtube.com/@axondeepseg8899). Would it be possible to move the video over there? It is currently uploaded on the neuropoly youtube channel.

The rest looks good to me. And thank you for creating a new video tutorial!

**Comment by mathieuboudreau** [comment]
>About the video: we have a youtube channel for AxonDeepSeg (https://www.youtube.com/@axondeepseg8899). Would it be possible to move the video over there? It is currently uploaded on the neuropoly youtube channel.

If I recall, we (the lab, internally) made the decision a year or two ago to stop using the individual "software project" Youtube videos, and centralize all new uploaded to the NeuroPoly Youtube channel. So I think the current SOP is still to upload to the common Neuropoly channel, we just never deleted the old software-specific ones.

**Review by mathieuboudreau — DISMISSED** [review]
Looks great to me @Stoyan-I-A! Some minor implementations internally I think could maybe be improved (eg how the axon or myelin pixel "values" are extracted from the axon-myelin mask), but I compared those instances with how they were implemented for the FSLeyes and they match exactly, so I think those are things I could look into later on to clean up and write tests for the plugin. In its current state, the plugin works almost identically to the FSLeyes plugin, which I think is what we want for an initial release. I expect some issues will be raised once more users get their hands on it, but as-is I think this is a high priority for release and after using it in a practical scenario this week pretty much flawlessly, I think it is ready to be released now.

Thank you so much @Stoyan-I-A !!

**Review by mathieuboudreau — DISMISSED** [review]
Re-approving, I just set the version of the plugin from 0.0.1 to 1.0.0

**Review by mathieuboudreau — APPROVED** [review]
Changed the pip installation of the repo in the GitHub Actions CI to match our user instructions: `pip install --verbose -e .` --> `pip install --verbose -e . plugins/`

**Pull request merged**
