### PR TITLE
Change "download_models" to "download_model"

### PR DESCRIPTION
**Pull request by mathieuboudreau**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://intranet.neuro.polymtl.ca/geek-tips/contributing#pr-labels-a-href-pr-labels-id-pr-labels-a) to this PR
- [ ] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [x] I've assigned a reviewer
- [ ] I've consulted [ADS's internal developer documentation](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution) to ensure my contribution is in line with any relevant design decisions

## Description

The documentation currently says to the users to call `download_model`, however our actual CLI command is `download_models`. As a simple fix, we can simply update the doc; however, it is a bit inconsistent that in actuality, our python **module** name is `download_model` (and makes more sense, since we can only download one model at a time I believe). So maybe changing the CLI command would be a better solution considering we're releasing 5.0 soon (this would require more changes though in the tests, installation, and CI files). Open to opinions/discussion

## Linked issues

#829

### CODE REVIEW

**Review by joshuacwnewton — DISMISSED** [review]
For comparison, SCT has a similar command called `sct_download_data`, so I think singular (`model`) does make sense.

But, as far as a documentation change goes, this LGTM!

**Comment by hermancollin** [comment]
Yeah I agree it should be the other way around. 

> So maybe changing the CLI command would be a better solution considering we're releasing 5.0 soon (this would require more changes though in the tests, installation, and CI files). Open to opinions/discussion.

Should we do this right now or merge this as a temporary fix and then open a new PR?

**Comment by mathieuboudreau** [comment]
>Should we do this right now or merge this as a temporary fix and then open a new PR?

I think we should do this now - let me see if I can catch all instances quickly

**Comment by mathieuboudreau** [comment]
@hermancollin I went that route and updated all the files (did a replace all in VS code), the tests pass so I think it would be safe to merge.

**Review by hermancollin — APPROVED** [review]
thank you for this fix

**Pull request merged**
