### PR TITLE
Segment images without patches

### LINKED ISSUE #676: Leverage "no patch" option soon to be released in IVADOMED
IVADOMED currently has a new feature (though not released in a pip version yet) that allows segmenting an image without patching during this step, which could resolve issues we occasionally encounter related to cutting the images in patches (eg straight lines that cut through the image masks).

There remains questions about what we'll want the default behaviour to be, because this is a memory intensive feature (not all computers will have suffiient RAM to work on images larger than a certain size, and this will vary between users).

We'll also need to test this feature vs our current behaviour on a range of test images (eg diffferent models, different axon sizes).

### PR DESCRIPTION
**Pull request by mariehbourget**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [ ] I've added relevant tests for my contribution
- [ ] I've updated the documentation and/or added correct docstrings
- [x] I've assigned a reviewer
- [x] I've consulted [ADS's internal developer documentation](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution) to ensure my contribution is in line with any relevant design decisions

## Description
This PR adds the option to segment without patches with the `--no-patch` flag in the CLI (as implemented in ivadomed v2.9.7).

The PR is still a draft, TODO:
- [x] Fix default overlap when using the no-patch option [here](https://github.com/axondeepseg/axondeepseg/blob/86a93308842a61175e0e75ddb8aeaae7fb2d6034/AxonDeepSeg/apply_model.py#L36)
- [x] Update documentation
- [x] Update docstrings
- [x] Add test

## Linked issues
Fixes #676

### CODE REVIEW

**Comment by mariehbourget** [comment]
This PR is now ready for review.
The new "no-patch" feature only applies to CLI and not to fsleyes where the behavior is unchanged,
@Stoyan-I-A, do you think we should integrate it in fsleyes or wait to do it in Napari?

**Comment by Stoyan-I-A** [comment]
It should be pretty easy to add this option in FSLeyes, so I'd say we should do it.
Now, should we do it in this PR or in another one?

**Comment by mariehbourget** [comment]
> It should be pretty easy to add this option in FSLeyes, so I'd say we should do it.
> Now, should we do it in this PR or in another one?

I would say probably separately because there is a small catch:
the "no-patch" option is supposed to be used without the "overlap" option. If both are used on the CLI, currently the "no-patch" option supersedes the "overlap" option and a warning is shown in the terminal from ivadomed.
So to make it clean in fsleyes, we would need to somehow disable the "overlap" option in the GUI when using the "no-patch" option. I don't know enough about the plugin to estimate if that is complicated or not.

**Comment by Stoyan-I-A** [comment]
> I would say probably separately

Ok, let's do it this way.

> we would need to somehow disable the "overlap" option in the GUI when using the "no-patch" option

For the user, I'm thinking of greying out (disabling) the "overlap" box in the settings menu when a no-patch checkbox is selected.

**Comment by mathieuboudreau** [comment]
Tests pass successfully on my local machine. I had to not only update my conda env (expected) but also re-do `pip install -e .` (thought for some reason that I wouldn't have to, but no-patch option wasn't working until I did so).

**Comment by mathieuboudreau** [comment]
Tested functionality with and without no patch option. I feel like just from this first test, the no-patch option results in better segmentation quality for several axons, in particular it fixes "irregular artifacts" in myelin.

## Without patching

image_seg-axonmyelin


## Without patching

image_seg-axonmyelin 2

## GIF


out

**Comment by mathieuboudreau** [comment]
Documentation looks good

**Comment by mathieuboudreau** [comment]
Thanks for adding a test [🎉](https://emojipedia.org/party-popper/)

**Review by mathieuboudreau — APPROVED** [review]
Looks great to me as is - thanks a lot @mariehbourget !

**Pull request merged**
