### PR TITLE
Auto-update ivadomed with `pip install -e .`

### LINKED ISSUE #623: Instructions on how to update ADS won't update the Ivadomed package
While testing #620, I encountered an error that was previously fixed on the Ivadomed side. This was because I didn't update the Ivadomed package in my environment.

Currently, in our docs, it says that we can update ADS by using these commands:
```
cd axondeepseg
git pull
pip install -e .
```

However, those instructions won't update the Ivadomed package. The user would need to do an additional command:
`pip install ivadomed==<The latest version supported by ADS>`.

Question: Will ADS always support the latest Ivadomed version? In this case, we would just need to add `pip install ivadomed` to the instructions. But if we insist on installing a fixed version, the user would have to check in the environment.yml file which version to install, which might be a bit cumbersome for the user.

### PR DESCRIPTION
**Pull request by hermancollin**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [ ] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [ ] I've assigned a reviewer
- [x] I've consulted [ADS's internal developer documentation](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution) to ensure my contribution is in line with any relevant design decisions

## Description

Extracts ivadomed's semantic version and runs an additionnal `pip install` command to update it at the end of the installation process. This way, when a user updates ADS using `pip install -e .`, the ivadomed version will be updated as well.

## Linked issues

Resolves #623

### CODE REVIEW

**Comment by hermancollin** [comment]
> Should we do this for all our pip packages? Maybe the function(s) could generalize to do so?

The other pip dependencies are
```
    - opencv-contrib-python
    - opencv-python-headless
    - torch==1.8.1+cpu; sys_platform != "darwin"
    - torchvision==0.9.1+cpu; sys_platform != "darwin"
    - torch==1.8.1;sys_platform == "darwin"
    - torchvision==0.9.1; sys_platform == "darwin"
```
opencv packages aren't pinned so I guess we don't want to update them? Also IIUC the sys_platform check is because torch/torchvision on macOS don't have separate cpu/gpu versions?

**Comment by mathieuboudreau** [comment]
> > Should we do this for all our pip packages? Maybe the function(s) could generalize to do so?
> 
> The other pip dependencies are
> 
> ```
>     - opencv-contrib-python
>     - opencv-python-headless
>     - torch==1.8.1+cpu; sys_platform != "darwin"
>     - torchvision==0.9.1+cpu; sys_platform != "darwin"
>     - torch==1.8.1;sys_platform == "darwin"
>     - torchvision==0.9.1; sys_platform == "darwin"
> ```
> 
> opencv packages aren't pinned so I guess we don't want to update them? Also IIUC the sys_platform check is because torch/torchvision on macOS don't have separate cpu/gpu versions?

I think one important note is that, automatically updating IVADOMED without updating torch/torch visions may introduce bugs, as it's possilbe that IVADOMED needs different versions of them in future updates, and this won't be communicated to us through your current PR (as they only document those requirements in their documentation, but they remain IVADOMED requirements nonetheless).

**Comment by hermancollin** [comment]
In that case it makes sense to add the torch/torchvision auto update as well.

It works on my system but I'm curious to see if it also does for Darwin

**Comment by Stoyan-I-A** [comment]
Command to update a conda environment:
(You need to deactivate the environment first)
`conda env update --name env_name --file environment.yml`

However, according to @hermancollin , this will not update the packages installed with pip

**Comment by hermancollin** [comment]
Actually we should close this PR in favor of changing the doc to tell the user that if he wants to update ADS, he should reinstall the whole environment. [This comment](https://github.com/axondeepseg/axondeepseg/issues/623#issuecomment-1119118046) sums up why it's a bad idea to go forward with this solution.

**Pull request closed without merging**
